### ISSUE TITLE
webpack is not used

### ISSUE THREAD

**Issue by ntraut** [ConnectProject/connect#21]
Currently, the documentation tells to do `yarn build` to build the react application but we way it is configured the application is only run from the source folder.

**Comment by r03ert0** [comment]
maybe make a branch, remove webpack there, test that nothing breaks, and then merge back?

**Comment by ntraut** [comment]
In fact the webpack build is used for the app in `src/connectServer.js` but the command `webpack-dev-server` fails because with this command the custom script `envConfig.js` used to access the environment variables at run time is not served.

There is also a problem in the docker file where `yarn build` is not used but the copy from the local directory allows to copy the build directory. I see a problem in the script `RegisterServiceWorker.jsx` which works only with a `NODE_ENV` set to production, for the moment it is never achieved.

**Comment by ntraut** [comment]
Solved by removing the service worker and no longer using the command `webpack-dev-server`.
