### ISSUE TITLE
github access token

### ISSUE THREAD

**Issue by ntraut** [ConnectProject/connect#23]
Currently developers use a predefined github access token, maybe it would be better to tell them how to create a new one.

**Comment by r03ert0** [comment]
the access token is not created when developers register their app?

**Comment by ntraut** [comment]
I was talking about developers who develop connect on a clone version. For developers who add their app in connect, the only thing they need to do is to login with github, for that they just need to give an authorization to the connect token, they don't need to create one.

**Comment by ntraut** [comment]
Fixed with #28
