### ISSUE TITLE
Service worker is not working

### ISSUE THREAD

**Issue by ntraut** [ConnectProject/connect#24]
When trying to run the `registerServiceWorker.jsx` script, after having fixed the environmental variable issues, the script fails because it tries to access a script named `service-worker.js` which doesn't exist anywhere in connect.

I'm not sure service worker has already been working, it's hard to figure as Matters guys wiped all the git history when they migrated from gitlab to github.

I think they used `create-react-app` to initially construct connect react app, but the new versions of `create-react-app` don't create those files, and it's not sure we can easily use an old version of `create-react-app` to construct a react app as it was before...

Maybe we could just forget about service worker, as it is not essential to run the app?

**Comment by r03ert0** [comment]
what do you think @morvanr?
I'd be ok for removing it. In fact, there's not a lot of GUI in connect. If it were not too difficult, I'd be for using vue instead of react.

**Comment by ntraut** [comment]
I saw that we can have an example app with a service worker by doing `create-react-app my-app-pwa --template cra-template-pwa`. But connect is not really an app designed to be accessed offline, so maybe we would be better to just remove this part.

**Comment by morvanr** [comment]
Hi guys, no clue on that one, I would think just as Nicolas : if it is of no use, just remove it... I don't quite see why we would need a worker on mavoix, but maybe it could be useful on other parts of connect I am not aware of !

**Comment by ntraut** [comment]
I think it would be more useful for mavoix because an offline feature would have an interest at the opposite of connect.
I was able to access the old git history of connect (which I don't know why they wiped it since it is still publicly available) and I can confirm that there never have been a `service-worker.js` script.
I will remove this functionality since it is not working and not useful.
